// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Order struct {
	ID            int32   `json:"id"`
	PaymentMethod string  `json:"payment_method"`
	Total         float64 `json:"total"`
	DatePurchase  string  `json:"date_purchase"`
	Status        string  `json:"status"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
}

type Query struct {
}
